#!/usr/bin/env perl

use strict;
use File::Temp qw/ tempfile tempdir /;
use Cwd; # like Unix pwd but more portable
use Getopt::Long qw(:config require_order);


    my $VERSION = sprintf "%d.%03d", q$Revision: 1.1 $ =~ /(\d+)/g;

    my $help = '';
    GetOptions ('help|?' => \$help);
    if ( $help || substr($ARGV[0],0,1) eq 'h' || @ARGV == 0 )
    {
        &print_usage();
        exit;
    }
    my $dir = shift;
    my $target = $dir;
    if (@ARGV > 1) 
    {
        $target = shift;
    }
    my $cvsroot = ":gserver:isscvs.cern.ch/local/reps/tdr";
    my $tmp_dir = tempdir() or die;
    my $orig_dir = Cwd::abs_path;
    chdir($tmp_dir);
    system("cvs -d $cvsroot co -l notes");
    chdir("notes");
    system("cvs -d $cvsroot -r update -d -f notes/$dir");
    local @ARGV;
    @ARGV = ( "--style", "an", "--wrap", "b", $target );
    local $0 = getcwd()."/tdr";
    eval { require( "tdr" ) };
    chdir($orig_dir);

###
sub print_usage {
    print "Usage: $0 note-dir note-name\n\nExample: $0 EXO-08-008 AN-09-035\n\n";
    print "        will tdr EXO-08-008/AN-09-035.tex\n\n";
    print "[when note-name and note-dir are identical except for the .tex]\n";
    print "       $0 note-name\nExample: $0 AN-09-035\n";
}

